db_retrieve_query = {'created_time': '2021-05-18T15:43:54.263Z',
 'id': 'fdd0105c-e747-400c-bb80-c1be62fa1cee',
 'last_edited_time': '2021-05-23T10:45:00.000Z',
 'object': 'database',
 'properties': {'Date Created': {'created_time': {},
                                 'id': "'Y6<",
                                 'type': 'created_time'},
                'Name': {'id': 'title', 'title': {}, 'type': 'title'},
                'Status': {'id': '^OE@',
                           'select': {'options': [{'color': 'red',
                                                   'id': '1',
                                                   'name': 'Backlog'},
                                                  {'color': 'yellow',
                                                   'id': '2',
                                                   'name': 'In Progress'},
                                                  {'color': 'green',
                                                   'id': '3',
                                                   'name': 'Done 🙌'},
                                                  {'color': 'blue',
                                                   'id': 'cd99652b-b8e5-4ef7-9a87-74029a1ea5c6',
                                                   'name': 'Today'}]},
                           'type': 'select'}},
 'title': [{'annotations': {'bold': False,
                            'code': False,
                            'color': 'default',
                            'italic': False,
                            'strikethrough': False,
                            'underline': False},
            'href': None,
            'plain_text': 'Task List',
            'text': {'content': 'Task List', 'link': None},
            'type': 'text'}]}

db_query_response_success = {'has_more': False,
             'next_cursor': None,
             'object': 'list',
             'results': [{'archived': False,
              'created_time': '2021-05-20T19:26:43.582Z',
              'id': '021f8a01-37e3-42db-9252-be02655cec7a',
              'last_edited_time': '2021-05-20T19:26:43.582Z',
              'object': 'page',
              'parent': {'database_id': 'fdd0105c-e747-400c-bb80-c1be62fa1cee',
                         'type': 'database_id'},
              'properties': {'Date Created': {'created_time': '2021-05-20T19:26:43.582Z',
                                              'id': "'Y6<",
                                              'type': 'created_time'},
                             'Name': {'id': 'title',
                                      'title': [{'annotations': {'bold': False,
                                                                 'code': False,
                                                                 'color': 'default',
                                                                 'italic': False,
                                                                 'strikethrough': False,
                                                                 'underline': False},
                                                 'href': None,
                                                 'plain_text': "uno",
                                                 'text': {'content': "uno",
                                                          'link': None},
                                                 'type': 'text'}],
                                      'type': 'title'},
                             'Status': {'id': '^OE@',
                                        'select': {'color': 'red',
                                                   'id': '1',
                                                   'name': 'Backlog'},
                                        'type': 'select'}}},
             {'archived': False,
              'created_time': '2021-05-20T08:23:00.000Z',
              'id': '0b88e8d3-428d-4015-9cd7-b468750bb3b5',
              'last_edited_time': '2021-05-20T08:24:00.000Z',
              'object': 'page',
              'parent': {'database_id': 'fdd0105c-e747-400c-bb80-c1be62fa1cee',
                         'type': 'database_id'},
              'properties': {'Date Created': {'created_time': '2021-05-20T08:23:00.000Z',
                                              'id': "'Y6<",
                                              'type': 'created_time'},
                             'Name': {'id': 'title',
                                      'title': [{'annotations': {'bold': False,
                                                                 'code': False,
                                                                 'color': 'default',
                                                                 'italic': False,
                                                                 'strikethrough': False,
                                                                 'underline': False},
                                                 'href': None,
                                                 'plain_text': 'dos',
                                                 'text': {'content': 'dos',
                                                          'link': None},
                                                 'type': 'text'}],
                                      'type': 'title'},
                             'Status': {'id': '^OE@',
                                        'select': {'color': 'red',
                                                   'id': '1',
                                                   'name': 'Backlog'},
                                        'type': 'select'}}},
             {'archived': False,
              'created_time': '2021-05-19T08:05:00.000Z',
              'id': 'fa5754b9-3980-4477-aa9c-92ecabb7568b',
              'last_edited_time': '2021-05-19T08:05:00.000Z',
              'object': 'page',
              'parent': {'database_id': 'fdd0105c-e747-400c-bb80-c1be62fa1cee',
                         'type': 'database_id'},
              'properties': {'Date Created': {'created_time': '2021-05-19T08:05:00.000Z',
                                              'id': "'Y6<",
                                              'type': 'created_time'},
                             'Name': {'id': 'title',
                                      'title': [{'annotations': {'bold': False,
                                                                 'code': False,
                                                                 'color': 'default',
                                                                 'italic': False,
                                                                 'strikethrough': False,
                                                                 'underline': False},
                                                 'href': None,
                                                 'plain_text': 'Tres',
                                                 'text': {'content': 'Tres',
                                                          'link': None},
                                                 'type': 'text'}],
                                      'type': 'title'},
                             'Status': {'id': '^OE@',
                                        'select': {'color': 'red',
                                                   'id': '1',
                                                   'name': 'Backlog'},
                                        'type': 'select'}}},]}
